name: 'Check Vim version'
description: 'Checking the version of installed Vim'
author: 'thinca <thinca@gmail.com>'

inputs:
  expected_vim_version:
    description: |-
      Version of Vim.
    required: true
  vim_type:
    description: |-
      Type of Vim.
      This is one of `vim`, `neovim`, or `macvim`.
    required: true
  gui:
    description: |-
      When this is `yes`, setups the GUI version.
      And `outputs.executable` points to GUI version of Vim.
    required: false
  arch:
    description: |-
      Architecture of Vim.
      This is either of `x86_64` or `x86`, enable when `vim_type` is `vim` on Windows.
    required: false
    default: 'x86_64'
  executable:
    description: |-
      The name of executable file.
    required: true
  executable_path:
    description: |-
      The full path of executable file.
    required: true
  use_executable_path:
    description: |-
      When this is `yes`, uses `executable_path` to execute Vim.
      This is for multiple install tests.
    required: false

branding:
  icon: 'check'
  color: 'green'

runs:
  using: 'node24'
  main: 'action.js'
